test: &default

  # Credentials for REST APIs
  client_id: AbOnwRDyu1utXuayIByGhpwmpP3t4MxiRlzC5Y3s4lmgq5fxScgP-L3osZK6
  client_secret: EIRQORABVFuA7HBemml_eCg8Q0cYGgEBhVd80LHsRNvk_rGNI_XeYhlg3Mgc

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: FitQikAPP-8AD87100L76968527
  username: paypal-facilitator_api1.leonsimmonds.com
  password: 1392938886
  signature: AnHc1gqKMtfhAvUHdzfi2h78ZvMxAoRx-wgGgrpcjNWZzNTR07LeogCi
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: paypal-facilitator@leonsimmonds.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
